# Source: https://github.com/neovim/nvim-lspconfig/blob/47a521e621570da77e25c31988e2b74412db25e4/.stylua.toml
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "None"
