# Source: https://github.com/neovim/nvim-lspconfig/blob/47a521e621570da77e25c31988e2b74412db25e4/neovim.yml
---
base: lua51

globals:
  vim:
    any: true
  assert:
    args:
      - type: bool
      - type: string
        required: false
  after_each:
    args:
      - type: function
  before_each:
    args:
      - type: function
  describe:
    args:
      - type: string
      - type: function
  it:
    args:
      - type: string
      - type: function
